name: Lighttpd

on:
  workflow_call:
  push:
    paths: 
      - 'imagens/lighttpd/**'
      - '!imagens/*/README.md'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./imagens/lighttpd/1.4.67-edge/Dockerfile.edge
            platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x
            tags: igorferreir4/lighttpd:edge
            cache: type=gha
            nomedocache: lighttpd-edge

          - dockerfile: ./imagens/lighttpd/1.4.64/Dockerfile.stable
            platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x
            tags: igorferreir4/lighttpd:1.4.64 , igorferreir4/lighttpd:latest
            cache: type=gha
            nomedocache: lighttpd-stable
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configurando QEMU
        uses: docker/setup-qemu-action@v2

      - name: Configurando Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Logando no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}   

      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          context: imagens/
          file: ${{ matrix.dockerfile }}
          platforms: ${{ matrix.platforms }}
          push: true
          tags: ${{ matrix.tags }}
          cache-from: ${{ matrix.cache }},scope=build-${{ matrix.nomedocache }}
          cache-to: ${{ matrix.cache }},scope=build-${{ matrix.nomedocache }},mode=max

      - name: Update README.md Docker
        uses: meeDamian/sync-readme@v1.0.6
        with:
          user: ${{ github.repository_owner }}
          pass: ${{ secrets.DOCKERHUB_TOKEN }}
          slug: igorferreir4/lighttpd
          readme: imagens/lighttpd/README.md
          description: lighttpd